name: Set up OCaml
description: Set up an OCaml and opam environment and add to PATH
author: Anil Madhavapeddy
branding:
  icon: package
  color: orange
inputs:
  allow-prerelease-opam:
    description: Allow to use a pre-release version of opam.
    required: false
    default: "false"
  ocaml-compiler:
    description: The OCaml compiler packages to initialise.
    required: true
  opam-repositories:
    description: The name and URL pair of the repository to fetch the packages from.
    required: false
    default: |
      default: git+https://github.com/ocaml/opam-repository.git
  opam-pin:
    description: Enable the automation feature for opam pin.
    required: false
    default: "true"
  opam-local-packages:
    description: The local packages to be used by `opam-pin`.
    required: false
    default: "*.opam"
  opam-disable-sandboxing:
    description: Disable the opam sandboxing feature.
    required: false
    default: "false"
  dune-cache:
    description: Enable the dune cache feature.
    required: false
    default: "false"
  cache-prefix:
    description: The prefix of the cache keys.
    required: false
    default: v1
  windows-environment:
    description: Whether to use `cygwin` (default) or `msys2` for windows installs.
    required: false
  github-token:
    description: DO NOT SET THIS.
    required: false
    default: ${{ github.token }}
runs:
  using: node20
  main: dist/index.js
  post: dist/post/index.js
  post-if: success()
