name: Deploy odoc
description: Generate documentation for your project and deploy it to GitHub Pages
author: Sora Morimoto
branding:
  icon: package
  color: orange
inputs:
  publish-dir:
    description: The directory where the document is stored
    required: false
    default: _build/default/_doc/_html
  destination-dir:
    description: The subdirectory to deploy
    required: false
    default: ""
  enable-jekyll:
    description: Enable the GitHub Pages built-in Jekyll
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - run: opam install . --deps-only --with-doc
      shell: bash
    - run: opam depext --install odoc
      shell: bash
    - run: opam exec -- dune build @doc
      shell: bash
    - name: Deploy odoc to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ${{ inputs.publish-dir }}
        destination_dir: ${{ inputs.destination-dir }}
        enable_jekyll: ${{ inputs.enable-jekyll }}
